### ISSUE TITLE
AWS EC2 instance service api url

### ISSUE THREAD

**Issue by ghltshubh** [globus/globus-sample-data-portal#60]
This should be https://YOUR_IP:5100/api instead of https://localhost:5100/api for hosting AWS EC2 instance.

**Comment by jaswilli** [comment]
Hi @ghltshubh,

For demonstration purposes the service is only meant to be used by the portal app, so setting it to `localhost` should be sufficient even on an ec2 instance.

If you're adapting the sample portal (and service) for your own purposes then yes, you might want to adjust that setting.
