### ISSUE TITLE
Question about the portal dataset

### ISSUE THREAD

**Issue by heather999** [globus/globus-sample-data-portal#62]
Hi, hope this is an appropriate place to ask a question.  I am struggling to understand the [`id` entries in the dataset.json file](https://github.com/globus/globus-sample-data-portal/blob/b378e8515f174e2bdb098c8212b9a62795727575/portal/data/datasets.json#L4).  At first I thought that corresponded to the endpoint id.  How is that id used in portal/views.py?
ah these are just any unique URI, I think  :)  Sorry for the noise

**Comment by jaswilli** [comment]
Hi,

Yes, they have no significance other than to provide a unique ID for the entries in the `dataset.json` file.

You're certainly welcome to ask questions here or send us an email at support@globus.org. We're always happy to help so feel free to reach out if there's anything else you're curious about or if you need any help.
