### ISSUE TITLE
Trouble running transfer using sample MRDP at https://mrdp.globus.org/

### ISSUE THREAD

**Issue by heather999** [globus/globus-sample-data-portal#63]
I have run the example MRDP: https://mrdp.globus.org/ before and successfully transferred data, even just a couple of weeks ago. However, yesterday I started to experience a problem in my own MRDP and wanted to confirm things were still working in the Globus example.  
So today, I visit: https://mrdp.globus.org/ and attempt a transfer of one of the airport collections.  After clicking Transfer, I am redirected to the Globus page to choose my endpoint.  I access my endpoint and I see the "Submit" button, which appears active, but is not.  I cannot click on it and there is no way now for me to start up the transfer.  This is the same behavior I started to experience with my own MRDP starting yesterday afternoon.
I've been in touch with Kyle Chard who mentioned he noticed there may have been an error on the Globus end, but I dont' have any more details beyond that.  Are there any known issues? Does the Globus MRDP https://mrdp.globus.org/ example work for others currently?

**Comment by jaswilli** [comment]
Hi,

Thanks for letting us know! We were able to reproduce the problem you're seeing and have released a fix. Please let us know if you're still having trouble and sorry for the inconvenience!
